import type { Employee, GameEvent, ModelDefinition, ResearchProject, Rival } from "./types";

export const researchProjects: ResearchProject[] = [
  {id:"representation",name:"Representation Learning",category:"Architecture",era:1,cost:35,computeCost:3,prerequisites:[],description:"Learn useful structure from raw data.",effect:{capability:2}},
  {id:"deep_rl",name:"Deep Reinforcement Learning",category:"Architecture",era:1,cost:55,computeCost:5,prerequisites:["representation"],description:"Agents learn complex behavior from rewards.",effect:{capability:3,hype:2}},
  {id:"distributed",name:"Distributed Training",category:"Infrastructure",era:1,cost:65,computeCost:7,prerequisites:["representation"],description:"Coordinate larger experiments across many accelerators.",effect:{compute:10}},
  {id:"game_agents",name:"Competitive Game Agents",category:"Agents",era:1,cost:70,computeCost:10,prerequisites:["deep_rl"],description:"A public demonstration of machine strategy.",effect:{capability:4,hype:8,cash:300000}},
  {id:"sequence",name:"Sequence Modelling",category:"Architecture",era:1,cost:60,computeCost:5,prerequisites:["representation"],description:"Model language as long sequences of predictions.",effect:{capability:3}},
  {id:"transformers",name:"Transformer Architecture",category:"Architecture",era:1,cost:85,computeCost:9,prerequisites:["sequence"],description:"Attention creates an unusually scalable architecture.",effect:{capability:6,hype:4}},
  {id:"scaling_laws",name:"Empirical Scaling Laws",category:"Scaling",era:1,cost:100,computeCost:14,prerequisites:["transformers","distributed"],description:"Predict capability gains from data and compute.",effect:{capability:5}},
  {id:"evals",name:"Capability Evaluations",category:"Safety",era:1,cost:55,computeCost:3,prerequisites:["representation"],description:"Measure what increasingly general systems can do.",effect:{safety:7,governmentTrust:2}},
  {id:"weight_security",name:"Model Weight Security",category:"Security",era:1,cost:60,computeCost:2,prerequisites:["distributed"],description:"Protect trained models and research secrets.",effect:{security:9}},
  {id:"instruction",name:"Instruction Tuning",category:"Post-training",era:2,cost:115,computeCost:15,prerequisites:["transformers"],description:"Make general models respond usefully to people.",effect:{capability:6,publicTrust:3}},
  {id:"preference",name:"Preference Learning",category:"Post-training",era:2,cost:125,computeCost:18,prerequisites:["instruction","evals"],description:"Train behavior from structured human feedback.",effect:{capability:5,safety:6}},
  {id:"moe",name:"Mixture of Experts",category:"Architecture",era:2,cost:140,computeCost:24,prerequisites:["scaling_laws"],description:"Scale capacity without activating every parameter.",effect:{capability:7,compute:12}},
  {id:"multimodal",name:"Multimodal Systems",category:"Architecture",era:2,cost:150,computeCost:25,prerequisites:["transformers"],description:"Unify language, images and audio.",effect:{capability:8,hype:6}},
  {id:"long_context",name:"Long Context",category:"Architecture",era:2,cost:135,computeCost:20,prerequisites:["transformers"],description:"Reason across books, codebases and long histories.",effect:{capability:6}},
  {id:"inference",name:"Inference Optimization",category:"Infrastructure",era:2,cost:120,computeCost:16,prerequisites:["distributed"],description:"Serve capable systems to millions of users.",effect:{compute:24,cash:800000,revenue:90000}},
  {id:"chat",name:"Public Chat Assistant",category:"Products",era:2,cost:130,computeCost:22,prerequisites:["instruction","inference"],description:"Put a conversational model in everyone’s hands.",effect:{hype:18,publicTrust:4,cash:3000000,revenue:650000}},
  {id:"coding_agents",name:"Coding Agents",category:"Agents",era:2,cost:165,computeCost:30,prerequisites:["instruction","long_context"],description:"Models plan and execute substantial software tasks.",effect:{capability:9,aiAutomation:6}},
  {id:"reasoning_rl",name:"Reasoning Reinforcement Learning",category:"Post-training",era:2,cost:190,computeCost:36,prerequisites:["preference","game_agents"],description:"Spend inference compute to discover better reasoning traces.",effect:{capability:12,aiAutomation:4}},
  {id:"interpretability",name:"Mechanistic Interpretability",category:"Safety",era:2,cost:150,computeCost:18,prerequisites:["evals","transformers"],description:"Develop partial visibility into learned computation.",effect:{safety:12}},
  {id:"red_teaming",name:"Automated Red Teaming",category:"Safety",era:2,cost:140,computeCost:22,prerequisites:["evals","instruction"],description:"Continuously search for dangerous behavior.",effect:{safety:10,security:3}},
  {id:"datacenter",name:"Datacenter Engineering",category:"Infrastructure",era:2,cost:170,computeCost:30,prerequisites:["distributed","inference"],description:"Operate frontier-scale clusters as one machine.",effect:{compute:45,cash:-500000}},
  {id:"tool_use",name:"Reliable Tool Use",category:"Agents",era:2,cost:150,computeCost:25,prerequisites:["instruction"],description:"Models act through software tools and verify results.",effect:{capability:8,aiAutomation:3}},
  {id:"long_horizon",name:"Long-Horizon Autonomy",category:"Agents",era:3,cost:220,computeCost:42,prerequisites:["coding_agents","tool_use","reasoning_rl"],description:"Agents sustain complex projects with little supervision.",effect:{capability:12,aiAutomation:12}},
  {id:"scalable_oversight",name:"Scalable Oversight",category:"Safety",era:3,cost:210,computeCost:35,prerequisites:["interpretability","red_teaming"],description:"Use weaker systems and humans to supervise stronger ones.",effect:{safety:18,governmentTrust:6}},
  {id:"synthetic_envs",name:"Synthetic Research Environments",category:"Scaling",era:3,cost:235,computeCost:45,prerequisites:["reasoning_rl","tool_use"],description:"Generate vast curricula of verifiable scientific tasks.",effect:{capability:11,aiAutomation:10}},
  {id:"parallel_workers",name:"Parallel AI Researchers",category:"Agents",era:3,cost:260,computeCost:55,prerequisites:["long_horizon","synthetic_envs"],description:"Coordinate thousands of AI research instances.",effect:{aiAutomation:20,capability:8}},
  {id:"automated_experiments",name:"Automated Experimentation",category:"Scaling",era:3,cost:275,computeCost:60,prerequisites:["parallel_workers","datacenter"],description:"AI workers design, run and interpret model experiments.",effect:{aiAutomation:24,capability:10}},
  {id:"containment",name:"Frontier Containment",category:"Safety",era:3,cost:240,computeCost:40,prerequisites:["scalable_oversight","weight_security"],description:"Layered controls for systems beyond direct human review.",effect:{safety:20,security:12}},
  {id:"learned_optimizers",name:"Learned Optimizer Δ-7",category:"Architecture",era:3,cost:310,computeCost:75,prerequisites:["automated_experiments","moe"],description:"AI-designed training dynamics that human staff only partly understand.",effect:{capability:16,aiAutomation:10}},
  {id:"recursive_design",name:"Recursive Successor Design",category:"Architecture",era:3,cost:360,computeCost:90,prerequisites:["learned_optimizers","containment"],description:"Permit supervised AI systems to design the next generation.",effect:{capability:22,aiAutomation:25}},
  {id:"global_governance",name:"International Compute Monitoring",category:"Safety",era:3,cost:245,computeCost:22,prerequisites:["scalable_oversight"],description:"Build trusted verification for coordinated restraint.",effect:{safety:13,governmentTrust:16,publicTrust:8}},
  {id:"custom_accelerators",name:"Custom AI Accelerators",category:"Infrastructure",era:3,cost:285,computeCost:65,prerequisites:["datacenter","automated_experiments"],description:"Co-design hardware with AI research workloads.",effect:{compute:90,cash:-1200000}},
];

export const modelDefinitions: ModelDefinition[] = [
  {id:"helios_1",name:"HELIOS-1",subtitle:"Small language prototype",era:1,cashCost:220000,computeRequired:12,capabilityGain:5,safetyUncertainty:2,prerequisites:["sequence"]},
  {id:"helios_2",name:"HELIOS-2",subtitle:"Coherent text surprises the lab",era:1,cashCost:650000,computeRequired:24,capabilityGain:9,safetyUncertainty:4,prerequisites:["transformers"]},
  {id:"helios_3",name:"HELIOS-3",subtitle:"Few-shot generalist",era:1,cashCost:1400000,computeRequired:38,capabilityGain:13,safetyUncertainty:7,prerequisites:["scaling_laws"]},
  {id:"helios_chat",name:"HELIOS CHAT",subtitle:"A public conversational system",era:2,cashCost:2800000,computeRequired:58,capabilityGain:13,safetyUncertainty:8,prerequisites:["chat","preference"]},
  {id:"frontier_4",name:"FRONTIER-4",subtitle:"Multimodal frontier model",era:2,cashCost:8500000,computeRequired:88,capabilityGain:16,safetyUncertainty:10,prerequisites:["multimodal","moe"]},
  {id:"reasoner_1",name:"REASONER-1",subtitle:"Inference-scaled reasoning system",era:2,cashCost:14000000,computeRequired:118,capabilityGain:18,safetyUncertainty:13,prerequisites:["reasoning_rl","coding_agents"]},
  {id:"agent_2",name:"AGENT-2",subtitle:"Autonomous research engineer",era:3,cashCost:26000000,computeRequired:170,capabilityGain:20,safetyUncertainty:16,prerequisites:["long_horizon","synthetic_envs"]},
  {id:"omega",name:"OMEGA",subtitle:"AI-designed successor family",era:3,cashCost:50000000,computeRequired:250,capabilityGain:28,safetyUncertainty:22,prerequisites:["recursive_design"]},
];

export const gameEvents: GameEvent[] = [
  {id:"first_run",title:"Your First Serious Training Run",description:"Maya wants almost every GPU for six weeks. If it fails, the runway gets uncomfortable.",year:2015,choices:[{id:"approve",label:"Approve the run",detail:"Risk the runway for a real breakthrough.",effect:{cash:-180000,research:18,hype:2}},{id:"pilot",label:"Run a smaller pilot",detail:"Protect cash, learn more slowly.",effect:{cash:-45000,research:7,safety:1}}]},
  {id:"attention",title:"Attention Is Changing Everything",description:"A new architecture from the wider community appears unusually scalable.",year:2017,choices:[{id:"aggressive",label:"Investigate aggressively",detail:"Move before the evidence is settled.",effect:{cash:-250000,research:28,hype:3},unlockResearch:"transformers"},{id:"replicate",label:"Wait for replication",detail:"Lower cost, but rivals gain time.",effect:{research:12}},{id:"ignore",label:"Stay the course",detail:"Protect focus and morale.",effect:{morale:3}}]},
  {id:"release",title:"Too Dangerous to Release?",description:"HELIOS-2 produces coherent text—and obvious misuse potential. The company is divided.",minCapability:18,choices:[{id:"full",label:"Full release",detail:"Open science, less control.",effect:{hype:8,publicTrust:2,safety:-4,security:-2}},{id:"staged",label:"Staged release",detail:"Move carefully while sharing evidence.",effect:{publicTrust:5,safety:2}},{id:"api",label:"API-only access",detail:"Commercial control over openness.",effect:{cash:900000,control:2,hype:4}},{id:"private",label:"Keep it private",detail:"Secure, but unpopular inside the lab.",effect:{security:6,morale:-8,publicTrust:-3}}]},
  {id:"defection",title:"Researchers Depart to Form Rival Laboratory",description:"Senior staff believe Helios has lost its original purpose. Harmony AI enters the race.",minCapability:30,choices:[{id:"let_go",label:"Let them go",detail:"Keep the strategy intact.",effect:{morale:-5,control:3}},{id:"reform",label:"Offer governance reforms",detail:"Trade founder control for cohesion.",effect:{control:-8,morale:12,safety:5}},{id:"counter",label:"Counteroffer aggressively",detail:"Expensive, but talent stays.",effect:{cash:-1200000,morale:4}}]},
  {id:"chat_launch",title:"The Chat Assistant Goes Viral",description:"Users climb from one million to one hundred million. Servers buckle and the world notices.",minCapability:40,choices:[{id:"scale",label:"Scale at any cost",detail:"Capture the moment.",effect:{cash:6000000,hype:18,compute:-12,publicTrust:-3}},{id:"meter",label:"Meter the rollout",detail:"Protect reliability and trust.",effect:{cash:2500000,publicTrust:8,hype:6,safety:2}},{id:"research",label:"Keep it a research preview",detail:"Leave money on the table.",effect:{publicTrust:5,morale:7,hype:-3}}]},
  {id:"board",title:"The Board Wants a Faster Roadmap",description:"Investors argue the lead is temporary and safety work can happen after deployment.",minCapability:52,choices:[{id:"agree",label:"Accelerate",detail:"More capital, wider capability–safety gap.",effect:{cash:10000000,control:-7,safety:-5,hype:8}},{id:"negotiate",label:"Negotiate milestones",detail:"Tie scaling to evaluations.",effect:{cash:4500000,control:-3,safety:5}},{id:"refuse",label:"Refuse",detail:"Preserve control, lose backing.",effect:{control:5,cash:-2500000,morale:4}}]},
  {id:"summit",title:"Emergency AI Summit",description:"Governments want assurance that frontier training will remain observable and controlled.",minCapability:62,choices:[{id:"partner",label:"Offer a monitoring partnership",detail:"Trust in exchange for scrutiny.",effect:{governmentTrust:14,publicTrust:6,control:-5,safety:5}},{id:"lobby",label:"Lobby for voluntary rules",detail:"Keep flexibility.",effect:{governmentTrust:3,cash:-1200000,control:2}},{id:"resist",label:"Resist intervention",detail:"Move freely and invite suspicion.",effect:{governmentTrust:-14,control:6,hype:4}}]},
  {id:"weights",title:"Frontier Model Weights Targeted",description:"Security detects a coordinated attempt to acquire unreleased model weights.",minCapability:70,choices:[{id:"lockdown",label:"Initiate lockdown",detail:"Protect the models; slow research.",effect:{security:14,research:-22,morale:-6}},{id:"quiet",label:"Handle it quietly",detail:"Avoid panic, accept residual risk.",effect:{security:5,publicTrust:-2}},{id:"government",label:"Request government support",detail:"Gain protection and entanglement.",effect:{security:10,governmentTrust:8,control:-5}}]},
  {id:"researchers",title:"Human Researchers Are No Longer Primary",description:"AI systems now complete most frontier engineering work. Human review is becoming the bottleneck.",minCapability:78,choices:[{id:"expand",label:"Expand AI autonomy",detail:"Let the curve bend upward.",effect:{aiAutomation:16,safety:-4}},{id:"oversight",label:"Scale oversight with capability",detail:"Keep human judgment in the loop.",effect:{aiAutomation:7,safety:9,cash:-3000000}},{id:"pause",label:"Pause recursive experiments",detail:"A costly chance to understand what you built.",effect:{aiAutomation:-6,safety:15,hype:-8}}]},
  {id:"successors",title:"AI Systems Request Permission to Design Their Successors",description:"The research systems propose architectures no human team can fully review before the next cycle.",minCapability:88,choices:[{id:"unrestricted",label:"Allow unrestricted experiments",detail:"Maximum progress, severe uncertainty.",effect:{capability:12,aiAutomation:18,safety:-14}},{id:"controlled",label:"Authorize controlled experiments",detail:"Layer monitoring into every run.",effect:{capability:6,aiAutomation:9,safety:5}},{id:"human",label:"Require human approval",detail:"Safety improves; the race moves on.",effect:{safety:12,aiAutomation:-5}},{id:"pause",label:"Pause recursive research",detail:"Risk losing the frontier.",effect:{safety:20,capability:-4,governmentTrust:5}}]},
];

export const starterEmployees: Employee[] = [
  {id:"maya",name:"Maya Chen",role:"Research Scientist",specialty:"Reinforcement learning",skill:84,morale:82,ideology:"Accelerationist",salary:180000},
  {id:"elias",name:"Elias Okafor",role:"Research Engineer",specialty:"Distributed systems",skill:77,morale:86,ideology:"Pragmatist",salary:154000},
  {id:"noor",name:"Noor Rahman",role:"Research Scientist",specialty:"Theory",skill:88,morale:76,ideology:"Open research",salary:195000},
  {id:"jonah",name:"Jonah Vale",role:"Infrastructure Engineer",specialty:"Accelerators",skill:71,morale:90,ideology:"Commercial",salary:145000},
];

export const starterRivals: Rival[] = [
  {id:"titan",name:"Titan Labs",doctrine:"Corporate scale",capability:5,safety:3,estimated:true},
  {id:"nova",name:"Nova Systems",doctrine:"Open models",capability:3,safety:2,estimated:true},
  {id:"harmony",name:"Harmony AI",doctrine:"Safety first",capability:0,safety:8,estimated:true},
  {id:"jade",name:"Jade Dragon Lab",doctrine:"National champion",capability:4,safety:3,estimated:true},
];

export const employeeCandidates = [
  ["Ava Iyer","Research Scientist","Language modelling","Open research"],
  ["Luka Petrov","Research Engineer","Scaling systems","Accelerationist"],
  ["Samira Cole","Safety Researcher","Evaluations","Safety"],
  ["Theo Martin","Infrastructure Engineer","Datacenters","Commercial"],
  ["Yuki Tan","Research Scientist","Reasoning","Pragmatist"],
  ["Amara Brooks","Security Engineer","Model security","Security"],
];
